2025-04-30 10:24:22,203 | INFO | Job Started
2025-04-30 10:24:22,203 | INFO | Logging run: /rds/general/user/psp20/home/Brain-Network/runs/stanford_dogs/batch_9/resnet_p63_20250430-102422
2025-04-30 10:24:22,549 | INFO | Using device: cuda
2025-04-30 10:24:22,549 | INFO | Training for 30 epochs
2025-04-30 10:24:22,549 | INFO | Debug mode: False
2025-04-30 10:24:22,549 | INFO | Downsampling by: 0.5
2025-04-30 10:24:22,549 | INFO | Auxiliary loss: {'loss_type': 0.01}
2025-04-30 10:24:22,550 | INFO | Train transforms: 
	Compose(
    RandomResizedCrop(size=(224, 224), scale=(0.8, 1), ratio=(0.75, 1.3333), interpolation=bilinear, antialias=True)
    RandomHorizontalFlip(p=0.5)
    ColorJitter(brightness=(0.8, 1.2), contrast=(0.8, 1.2), saturation=(0.8, 1.2), hue=None)
    ToTensor()
    Normalize(mean=(0.4765, 0.4517, 0.3911), std=(0.2264, 0.2214, 0.2193))
)
2025-04-30 10:24:22,550 | INFO | Test transforms: 
	Compose(
    Resize(size=[224, 224], interpolation=bilinear, max_size=None, antialias=True)
    ToTensor()
    Normalize(mean=(0.4765, 0.4517, 0.3911), std=(0.2264, 0.2214, 0.2193))
)
2025-04-30 10:24:22,763 | INFO | Downsampling by: 0.5. Few shot: False
2025-04-30 10:24:23,060 | INFO | Label smoothing: 0.1
2025-04-30 10:24:23,060 | INFO | Auxiliary loss: {'loss_type': 0.01}
2025-04-30 10:25:10,678 | INFO | Epoch: 1 | Time: 47.62s
2025-04-30 10:25:10,678 | ERROR | Error occured
Traceback (most recent call last):
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 444, in main
    best_loss_model, last_model, train_losses, val_losses, train_acc, val_acc = train_model(
                                                                                ^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 206, in train_model
    logger.info(f"Train Loss={avg_train_loss:.4f}, Train Acc={train_acc:.2f}%, Train Gamma Loss={avg_train_gamma_loss:.4f}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'avg_train_gamma_loss' where it is not associated with a value
