mv: cannot stat 'job_logs/train.err': No such file or directory
Starting training on cx3-20-0.cx3.hpc.ic.ac.uk at Mon 28 Apr 15:27:39 BST 2025
Using config: configs/stanford_dogs/zoomvit_configs/config_zoomvit_p36.json
Traceback (most recent call last):
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 568, in <module>
    main()
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 445, in main
    ).to(device)
      ^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Finished at Mon 28 Apr 15:28:43 BST 2025

====================================
CPU Time used: 00:00:03
CPU Percent: 6%
Memory usage: 475372kb
Approx Power usage: 0.0
Walltime usage: 00:01:14

====================================
